name = "auth-backend"
main = "src/index.ts"
compatibility_date = "2022-12-30"
node_compat = true

[vars]
AUTH_API_KEY = "AIzaSyAdmg-M42WaSQacbWa_-45mnhLPl5agzBE"
AUTH_DOMAIN = "starpy.me"
AUTH_PROJECT_ID = "starpy"
AUTH_STORAGE_BUCKET = "starpy.appspot.com"
AUTH_MESSAGING_SENDER_ID = "1012103782424"
AUTH_APP_ID = "1:1012103782424:web:119d7746a26fbbe688636d"
AUTH_MESUAREMENT_I = "G-TGXM40S8J8"